#problem 2:Even fibonacci numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(upto=100):
    sequence = [1,2]
    while (sequence[len(sequence)-1]+sequence[len(sequence)-2]) <= upto:
        lastInSeq = len(sequence)-1
        nextFib = sequence[lastInSeq] + sequence[lastInSeq-1]
        sequence.append(nextFib)
    return sequence
def even(num):
    if num % 2 ==0: return True
    else: False
#solution
print(sum(list(filter(even,fibonacci(4*10**6)))))
