#Problem 45: Triangular, pentagonal, and hexagonal
""" Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal. """
from itertools import combinations
import time
from xml.etree.ElementTree import TreeBuilder
triNums = {1:1, 2:3}
def triangleNumber(n):
    #memoized
    if n in triNums.keys():
        return triNums[n]
    else:
        ans = (n*(n+1))/2
        triNums[n] = ans
        return int(ans)
pentNums = {1:1, 2:5}
def pentagonNumber(n):
    #memoized
    if n in pentNums.keys():
        return pentNums[n]
    else:
        ans = (n*((3*n)-1))/2
        pentNums[n] = ans
        return int(ans)
hexNums = {1:1, 2:6}
def hexagonNumber(n):
    #memoized
    if n in hexNums.keys():
        return hexNums[n]
    else:
        ans = (n)*((2*n)-1)
        hexNums[n] = ans
        return int(ans)

sttime = time.time()

numsInCommon=[]
n=2
while True:
    t = triangleNumber(n)
    p = pentagonNumber(n)
    h = hexagonNumber(n)
    if (t in hexNums.values()) and (t in pentNums.values()) and t !=40755: numsInCommon = [t]
    if numsInCommon!=[]:
        break
    n+=1
print(numsInCommon)

print("time to find next tri hex and pent number after 40755: ",time.time()-sttime)